//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceConsultas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConsultas.IServiceConsultas")]
    public interface IServiceConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/ConsultarTickets", ReplyAction="http://tempuri.org/IServiceConsultas/ConsultarTicketsResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarTickets(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> canales, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/ConsultarEficienciaTickets", ReplyAction="http://tempuri.org/IServiceConsultas/ConsultarEficienciaTicketsResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarEficienciaTickets(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/ConsultarHits", ReplyAction="http://tempuri.org/IServiceConsultas/ConsultarHitsResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperHits> ConsultarHits(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/ConsultarEncuestas", ReplyAction="http://tempuri.org/IServiceConsultas/ConsultarEncuestasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarEncuestas(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/ConsultaEncuestaPregunta", ReplyAction="http://tempuri.org/IServiceConsultas/ConsultaEncuestaPreguntaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultaEncuestaPregunta(int idUsuario, int idEncuesta, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha, int tipoEncuesta, int idPregunta, int respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaTicket", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaTicketResponse")]
        System.Data.DataTable GraficarConsultaTicket(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaTicketGeografico", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaTicketGeograficoResponse")]
        string GraficarConsultaTicketGeografico(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaHits", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaHitsResponse")]
        System.Data.DataTable GraficarConsultaHits(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaHitsGeografico", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaHitsGeograficoResponse")]
        string GraficarConsultaHitsGeografico(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuesta", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaResponse")]
        System.Data.DataTable GraficarConsultaEncuesta(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaGeografica", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaGeograficaResponse")]
        string GraficarConsultaEncuestaGeografica(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaPregunta", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaPreguntaResponse")]
        System.Collections.Generic.List<System.Data.DataTable> GraficarConsultaEncuestaPregunta(int idUsuario, int idEncuesta, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha, int tipoEncuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaPreguntaGeografica", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEncuestaPreguntaGeograficaRe" +
            "sponse")]
        string GraficarConsultaEncuestaPreguntaGeografica(int idUsuario, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEficienciaTicket", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEficienciaTicketResponse")]
        System.Data.DataTable GraficarConsultaEficienciaTicket(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, string stack, int tipoFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultas/GraficarConsultaEEficienciaTicketsGeografica" +
            "", ReplyAction="http://tempuri.org/IServiceConsultas/GraficarConsultaEEficienciaTicketsGeografica" +
            "Response")]
        string GraficarConsultaEEficienciaTicketsGeografica(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceConsultasChannel : KiiniHelp.ServiceConsultas.IServiceConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceConsultasClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceConsultas.IServiceConsultas>, KiiniHelp.ServiceConsultas.IServiceConsultas {
        
        public ServiceConsultasClient() {
        }
        
        public ServiceConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarTickets(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> canales, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int pageIndex, int pageSize) {
            return base.Channel.ConsultarTickets(idUsuario, grupos, canales, tiposUsuario, organizaciones, ubicaciones, tipoArbol, tipificacion, prioridad, estatus, sla, vip, fechas, pageIndex, pageSize);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarEficienciaTickets(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int pageIndex, int pageSize) {
            return base.Channel.ConsultarEficienciaTickets(idUsuario, grupos, responsables, tipoArbol, tipificacion, nivelAtencion, atendedores, fechas, tiposUsuario, prioridad, ubicaciones, organizaciones, vip, pageIndex, pageSize);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperHits> ConsultarHits(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int pageIndex, int pageSize) {
            return base.Channel.ConsultarHits(idUsuario, grupos, tiposUsuario, organizaciones, ubicaciones, tipificacion, vip, fechas, pageIndex, pageSize);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultarEncuestas(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int pageIndex, int pageSize) {
            return base.Channel.ConsultarEncuestas(idUsuario, grupos, tipoArbol, responsables, encuestas, atendedores, fechas, tiposUsuario, prioridad, sla, ubicaciones, organizaciones, vip, pageIndex, pageSize);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperReportesTicket> ConsultaEncuestaPregunta(int idUsuario, int idEncuesta, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha, int tipoEncuesta, int idPregunta, int respuesta) {
            return base.Channel.ConsultaEncuestaPregunta(idUsuario, idEncuesta, fechas, tipoFecha, tipoEncuesta, idPregunta, respuesta);
        }
        
        public System.Data.DataTable GraficarConsultaTicket(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha) {
            return base.Channel.GraficarConsultaTicket(idUsuario, grupos, tiposUsuario, organizaciones, ubicaciones, tipoArbol, tipificacion, prioridad, estatus, sla, vip, fechas, filtroStackColumn, stack, tipoFecha);
        }
        
        public string GraficarConsultaTicketGeografico(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> estatus, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha) {
            return base.Channel.GraficarConsultaTicketGeografico(idUsuario, grupos, tiposUsuario, organizaciones, ubicaciones, tipoArbol, tipificacion, prioridad, estatus, sla, vip, fechas, filtroStackColumn, stack, tipoFecha);
        }
        
        public System.Data.DataTable GraficarConsultaHits(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha) {
            return base.Channel.GraficarConsultaHits(idUsuario, grupos, tiposUsuario, organizaciones, ubicaciones, tipificacion, vip, fechas, filtroStackColumn, stack, tipoFecha);
        }
        
        public string GraficarConsultaHitsGeografico(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<System.Nullable<bool>> vip, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> filtroStackColumn, string stack, int tipoFecha) {
            return base.Channel.GraficarConsultaHitsGeografico(idUsuario, grupos, tiposUsuario, organizaciones, ubicaciones, tipificacion, vip, fechas, filtroStackColumn, stack, tipoFecha);
        }
        
        public System.Data.DataTable GraficarConsultaEncuesta(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha) {
            return base.Channel.GraficarConsultaEncuesta(idUsuario, grupos, tipoArbol, responsables, encuestas, atendedores, fechas, tiposUsuario, prioridad, sla, ubicaciones, organizaciones, vip, tipoFecha);
        }
        
        public string GraficarConsultaEncuestaGeografica(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<System.Nullable<bool>> sla, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha) {
            return base.Channel.GraficarConsultaEncuestaGeografica(idUsuario, grupos, tipoArbol, responsables, encuestas, atendedores, fechas, tiposUsuario, prioridad, sla, ubicaciones, organizaciones, vip, tipoFecha);
        }
        
        public System.Collections.Generic.List<System.Data.DataTable> GraficarConsultaEncuestaPregunta(int idUsuario, int idEncuesta, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha, int tipoEncuesta) {
            return base.Channel.GraficarConsultaEncuestaPregunta(idUsuario, idEncuesta, fechas, tipoFecha, tipoEncuesta);
        }
        
        public string GraficarConsultaEncuestaPreguntaGeografica(int idUsuario, System.Collections.Generic.List<System.Nullable<int>> encuestas, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, int tipoFecha) {
            return base.Channel.GraficarConsultaEncuestaPreguntaGeografica(idUsuario, encuestas, fechas, tipoFecha);
        }
        
        public System.Data.DataTable GraficarConsultaEficienciaTicket(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, string stack, int tipoFecha) {
            return base.Channel.GraficarConsultaEficienciaTicket(idUsuario, grupos, responsables, tipoArbol, tipificacion, nivelAtencion, atendedores, fechas, tiposUsuario, prioridad, ubicaciones, organizaciones, vip, stack, tipoFecha);
        }
        
        public string GraficarConsultaEEficienciaTicketsGeografica(int idUsuario, System.Collections.Generic.List<int> grupos, System.Collections.Generic.List<int> responsables, System.Collections.Generic.List<int> tipoArbol, System.Collections.Generic.List<int> tipificacion, System.Collections.Generic.List<int> nivelAtencion, System.Collections.Generic.List<int> atendedores, System.Collections.Generic.Dictionary<string, System.DateTime> fechas, System.Collections.Generic.List<int> tiposUsuario, System.Collections.Generic.List<int> prioridad, System.Collections.Generic.List<int> ubicaciones, System.Collections.Generic.List<int> organizaciones, System.Collections.Generic.List<System.Nullable<bool>> vip, int tipoFecha) {
            return base.Channel.GraficarConsultaEEficienciaTicketsGeografica(idUsuario, grupos, responsables, tipoArbol, tipificacion, nivelAtencion, atendedores, fechas, tiposUsuario, prioridad, ubicaciones, organizaciones, vip, tipoFecha);
        }
    }
}
