//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaRol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaRol.IServiceRoles")]
    public interface IServiceRoles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoles/ObtenerRoles", ReplyAction="http://tempuri.org/IServiceRoles/ObtenerRolesResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Rol> ObtenerRoles(int idTipoUsuario, bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRolesChannel : KiiniHelp.ServiceSistemaRol.IServiceRoles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRolesClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaRol.IServiceRoles>, KiiniHelp.ServiceSistemaRol.IServiceRoles {
        
        public ServiceRolesClient() {
        }
        
        public ServiceRolesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRolesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRolesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRolesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Rol> ObtenerRoles(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerRoles(idTipoUsuario, insertarSeleccion);
        }
    }
}
