//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceAtencionTicket {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAtencionTicket.IServiceAtencionTicket")]
    public interface IServiceAtencionTicket {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/AutoAsignarTicket", ReplyAction="http://tempuri.org/IServiceAtencionTicket/AutoAsignarTicketResponse")]
        void AutoAsignarTicket(int idTicket, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/CambiarEstatus", ReplyAction="http://tempuri.org/IServiceAtencionTicket/CambiarEstatusResponse")]
        void CambiarEstatus(int idTicket, int idEstatus, int idUsuario, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/CambiarAsignacionTicket", ReplyAction="http://tempuri.org/IServiceAtencionTicket/CambiarAsignacionTicketResponse")]
        void CambiarAsignacionTicket(int idTicket, int idEstatusAsignacion, int idUsuarioAsignado, int idNivelAsignado, int idUsuarioAsigna, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/AgregarComentarioConversacionTicket", ReplyAction="http://tempuri.org/IServiceAtencionTicket/AgregarComentarioConversacionTicketResp" +
            "onse")]
        void AgregarComentarioConversacionTicket(int idTicket, int idUsuario, string mensaje, bool sistema, System.Collections.Generic.List<string> archivos, bool privado, bool enviaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/MarcarAsignacionLeida", ReplyAction="http://tempuri.org/IServiceAtencionTicket/MarcarAsignacionLeidaResponse")]
        void MarcarAsignacionLeida(int idAsignacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/ObtenerTicketEnAtencion", ReplyAction="http://tempuri.org/IServiceAtencionTicket/ObtenerTicketEnAtencionResponse")]
        KiiniNet.Entities.Helper.HelperticketEnAtencion ObtenerTicketEnAtencion(int idTicket, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAtencionTicket/ObtenerNumeroTicketsEnAtencionNuevos", ReplyAction="http://tempuri.org/IServiceAtencionTicket/ObtenerNumeroTicketsEnAtencionNuevosRes" +
            "ponse")]
        int ObtenerNumeroTicketsEnAtencionNuevos(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAtencionTicketChannel : KiiniHelp.ServiceAtencionTicket.IServiceAtencionTicket, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAtencionTicketClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceAtencionTicket.IServiceAtencionTicket>, KiiniHelp.ServiceAtencionTicket.IServiceAtencionTicket {
        
        public ServiceAtencionTicketClient() {
        }
        
        public ServiceAtencionTicketClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAtencionTicketClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAtencionTicketClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAtencionTicketClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AutoAsignarTicket(int idTicket, int idUsuario) {
            base.Channel.AutoAsignarTicket(idTicket, idUsuario);
        }
        
        public void CambiarEstatus(int idTicket, int idEstatus, int idUsuario, string comentario) {
            base.Channel.CambiarEstatus(idTicket, idEstatus, idUsuario, comentario);
        }
        
        public void CambiarAsignacionTicket(int idTicket, int idEstatusAsignacion, int idUsuarioAsignado, int idNivelAsignado, int idUsuarioAsigna, string comentario) {
            base.Channel.CambiarAsignacionTicket(idTicket, idEstatusAsignacion, idUsuarioAsignado, idNivelAsignado, idUsuarioAsigna, comentario);
        }
        
        public void AgregarComentarioConversacionTicket(int idTicket, int idUsuario, string mensaje, bool sistema, System.Collections.Generic.List<string> archivos, bool privado, bool enviaCorreo) {
            base.Channel.AgregarComentarioConversacionTicket(idTicket, idUsuario, mensaje, sistema, archivos, privado, enviaCorreo);
        }
        
        public void MarcarAsignacionLeida(int idAsignacion) {
            base.Channel.MarcarAsignacionLeida(idAsignacion);
        }
        
        public KiiniNet.Entities.Helper.HelperticketEnAtencion ObtenerTicketEnAtencion(int idTicket, int idUsuario) {
            return base.Channel.ObtenerTicketEnAtencion(idTicket, idUsuario);
        }
        
        public int ObtenerNumeroTicketsEnAtencionNuevos(int idUsuario) {
            return base.Channel.ObtenerNumeroTicketsEnAtencionNuevos(idUsuario);
        }
    }
}
