//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceDiasHorario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDiasHorario.IServiceDiasHorario")]
    public interface IServiceDiasHorario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioDefault", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioDefaultResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioDefault(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioConsulta", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioConsulta(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/CrearHorario", ReplyAction="http://tempuri.org/IServiceDiasHorario/CrearHorarioResponse")]
        void CrearHorario(KiiniNet.Entities.Cat.Usuario.Horario horario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ActualizarHorario", ReplyAction="http://tempuri.org/IServiceDiasHorario/ActualizarHorarioResponse")]
        void ActualizarHorario(KiiniNet.Entities.Cat.Usuario.Horario horario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioById", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioByIdResponse")]
        KiiniNet.Entities.Cat.Usuario.Horario ObtenerHorarioById(int idHorario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/HabilitarHorario", ReplyAction="http://tempuri.org/IServiceDiasHorario/HabilitarHorarioResponse")]
        void HabilitarHorario(int idHorario, bool habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosConsulta", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiasFeriados> ObtenerDiasFeriadosConsulta(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiasDefault", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiasDefaultResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiaFestivoDefault> ObtenerDiasDefault(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/AgregarDiaFeriado", ReplyAction="http://tempuri.org/IServiceDiasHorario/AgregarDiaFeriadoResponse")]
        void AgregarDiaFeriado(KiiniNet.Entities.Cat.Usuario.DiaFeriado dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiaByFecha", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiaByFechaResponse")]
        KiiniNet.Entities.Cat.Usuario.DiaFeriado ObtenerDiaByFecha(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiaFeriado", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiaFeriadoResponse")]
        KiiniNet.Entities.Cat.Usuario.DiaFeriado ObtenerDiaFeriado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriados", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiaFeriado> ObtenerDiasFeriados(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ActualizarDiasFestivos", ReplyAction="http://tempuri.org/IServiceDiasHorario/ActualizarDiasFestivosResponse")]
        void ActualizarDiasFestivos(KiiniNet.Entities.Cat.Usuario.DiasFeriados item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/CrearDiasFestivos", ReplyAction="http://tempuri.org/IServiceDiasHorario/CrearDiasFestivosResponse")]
        void CrearDiasFestivos(KiiniNet.Entities.Cat.Usuario.DiasFeriados item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosUser", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosUserResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiasFeriados> ObtenerDiasFeriadosUser(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosUserById", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerDiasFeriadosUserByIdResponse")]
        KiiniNet.Entities.Cat.Usuario.DiasFeriados ObtenerDiasFeriadosUserById(int idCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/HabilitarDiasFestivos", ReplyAction="http://tempuri.org/IServiceDiasHorario/HabilitarDiasFestivosResponse")]
        void HabilitarDiasFestivos(int idDiasFestivos, bool habilitado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDiasHorarioChannel : KiiniHelp.ServiceDiasHorario.IServiceDiasHorario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDiasHorarioClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceDiasHorario.IServiceDiasHorario>, KiiniHelp.ServiceDiasHorario.IServiceDiasHorario {
        
        public ServiceDiasHorarioClient() {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDiasHorarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioDefault(bool insertarSeleccion) {
            return base.Channel.ObtenerHorarioDefault(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioConsulta(string filtro) {
            return base.Channel.ObtenerHorarioConsulta(filtro);
        }
        
        public void CrearHorario(KiiniNet.Entities.Cat.Usuario.Horario horario) {
            base.Channel.CrearHorario(horario);
        }
        
        public void ActualizarHorario(KiiniNet.Entities.Cat.Usuario.Horario horario) {
            base.Channel.ActualizarHorario(horario);
        }
        
        public KiiniNet.Entities.Cat.Usuario.Horario ObtenerHorarioById(int idHorario) {
            return base.Channel.ObtenerHorarioById(idHorario);
        }
        
        public void HabilitarHorario(int idHorario, bool habilitado) {
            base.Channel.HabilitarHorario(idHorario, habilitado);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiasFeriados> ObtenerDiasFeriadosConsulta(string filtro) {
            return base.Channel.ObtenerDiasFeriadosConsulta(filtro);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiaFestivoDefault> ObtenerDiasDefault(bool insertarSeleccion) {
            return base.Channel.ObtenerDiasDefault(insertarSeleccion);
        }
        
        public void AgregarDiaFeriado(KiiniNet.Entities.Cat.Usuario.DiaFeriado dia) {
            base.Channel.AgregarDiaFeriado(dia);
        }
        
        public KiiniNet.Entities.Cat.Usuario.DiaFeriado ObtenerDiaByFecha(System.DateTime fecha) {
            return base.Channel.ObtenerDiaByFecha(fecha);
        }
        
        public KiiniNet.Entities.Cat.Usuario.DiaFeriado ObtenerDiaFeriado(int id) {
            return base.Channel.ObtenerDiaFeriado(id);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiaFeriado> ObtenerDiasFeriados(bool insertarSeleccion) {
            return base.Channel.ObtenerDiasFeriados(insertarSeleccion);
        }
        
        public void ActualizarDiasFestivos(KiiniNet.Entities.Cat.Usuario.DiasFeriados item) {
            base.Channel.ActualizarDiasFestivos(item);
        }
        
        public void CrearDiasFestivos(KiiniNet.Entities.Cat.Usuario.DiasFeriados item) {
            base.Channel.CrearDiasFestivos(item);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.DiasFeriados> ObtenerDiasFeriadosUser(bool insertarSeleccion) {
            return base.Channel.ObtenerDiasFeriadosUser(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Usuario.DiasFeriados ObtenerDiasFeriadosUserById(int idCatalogo) {
            return base.Channel.ObtenerDiasFeriadosUserById(idCatalogo);
        }
        
        public void HabilitarDiasFestivos(int idDiasFestivos, bool habilitado) {
            base.Channel.HabilitarDiasFestivos(idDiasFestivos, habilitado);
        }
    }
}
