//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaTipoInformacionConsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaTipoInformacionConsulta.IServiceTipoInfConsulta")]
    public interface IServiceTipoInfConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoInfConsulta/ObtenerTipoInformacionConsulta", ReplyAction="http://tempuri.org/IServiceTipoInfConsulta/ObtenerTipoInformacionConsultaResponse" +
            "")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoInfConsulta> ObtenerTipoInformacionConsulta(bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoInfConsultaChannel : KiiniHelp.ServiceSistemaTipoInformacionConsulta.IServiceTipoInfConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoInfConsultaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaTipoInformacionConsulta.IServiceTipoInfConsulta>, KiiniHelp.ServiceSistemaTipoInformacionConsulta.IServiceTipoInfConsulta {
        
        public ServiceTipoInfConsultaClient() {
        }
        
        public ServiceTipoInfConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoInfConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoInfConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoInfConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoInfConsulta> ObtenerTipoInformacionConsulta(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoInformacionConsulta(insertarSeleccion);
        }
    }
}
