//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaTipoTelefono {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaTipoTelefono.IServiceTipoTelefono")]
    public interface IServiceTipoTelefono {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTelefono/ObtenerTiposTelefono", ReplyAction="http://tempuri.org/IServiceTipoTelefono/ObtenerTiposTelefonoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoTelefono> ObtenerTiposTelefono(bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoTelefonoChannel : KiiniHelp.ServiceSistemaTipoTelefono.IServiceTipoTelefono, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoTelefonoClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaTipoTelefono.IServiceTipoTelefono>, KiiniHelp.ServiceSistemaTipoTelefono.IServiceTipoTelefono {
        
        public ServiceTipoTelefonoClient() {
        }
        
        public ServiceTipoTelefonoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoTelefonoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoTelefonoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoTelefonoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoTelefono> ObtenerTiposTelefono(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposTelefono(insertarSeleccion);
        }
    }
}
