//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServicePuesto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePuesto.IServicePuesto")]
    public interface IServicePuesto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/ObtenerPuestosByTipoUsuario", ReplyAction="http://tempuri.org/IServicePuesto/ObtenerPuestosByTipoUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Puesto> ObtenerPuestosByTipoUsuario(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/ObtenerPuestoById", ReplyAction="http://tempuri.org/IServicePuesto/ObtenerPuestoByIdResponse")]
        KiiniNet.Entities.Cat.Usuario.Puesto ObtenerPuestoById(int idPuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/Guardar", ReplyAction="http://tempuri.org/IServicePuesto/GuardarResponse")]
        void Guardar(KiiniNet.Entities.Cat.Usuario.Puesto puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/Actualizar", ReplyAction="http://tempuri.org/IServicePuesto/ActualizarResponse")]
        void Actualizar(int idPuesto, KiiniNet.Entities.Cat.Usuario.Puesto puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/ObtenerPuestoConsulta", ReplyAction="http://tempuri.org/IServicePuesto/ObtenerPuestoConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Puesto> ObtenerPuestoConsulta(System.Nullable<int> idTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePuesto/Habilitar", ReplyAction="http://tempuri.org/IServicePuesto/HabilitarResponse")]
        void Habilitar(int idPuesto, bool habilitado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePuestoChannel : KiiniHelp.ServicePuesto.IServicePuesto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePuestoClient : System.ServiceModel.ClientBase<KiiniHelp.ServicePuesto.IServicePuesto>, KiiniHelp.ServicePuesto.IServicePuesto {
        
        public ServicePuestoClient() {
        }
        
        public ServicePuestoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePuestoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePuestoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePuestoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Puesto> ObtenerPuestosByTipoUsuario(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerPuestosByTipoUsuario(idTipoUsuario, insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Usuario.Puesto ObtenerPuestoById(int idPuesto) {
            return base.Channel.ObtenerPuestoById(idPuesto);
        }
        
        public void Guardar(KiiniNet.Entities.Cat.Usuario.Puesto puesto) {
            base.Channel.Guardar(puesto);
        }
        
        public void Actualizar(int idPuesto, KiiniNet.Entities.Cat.Usuario.Puesto puesto) {
            base.Channel.Actualizar(idPuesto, puesto);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Puesto> ObtenerPuestoConsulta(System.Nullable<int> idTipoUsuario) {
            return base.Channel.ObtenerPuestoConsulta(idTipoUsuario);
        }
        
        public void Habilitar(int idPuesto, bool habilitado) {
            base.Channel.Habilitar(idPuesto, habilitado);
        }
    }
}
