//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceNota {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNota.IServiceNota")]
    public interface IServiceNota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/CrearNotaGeneralUsuario", ReplyAction="http://tempuri.org/IServiceNota/CrearNotaGeneralUsuarioResponse")]
        void CrearNotaGeneralUsuario(KiiniNet.Entities.Operacion.NotaGeneral notaGeneral);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/CrearNotaOpcionUsuario", ReplyAction="http://tempuri.org/IServiceNota/CrearNotaOpcionUsuarioResponse")]
        void CrearNotaOpcionUsuario(KiiniNet.Entities.Operacion.NotaOpcionUsuario notaOpcionUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/CrearNotaOpcionGrupo", ReplyAction="http://tempuri.org/IServiceNota/CrearNotaOpcionGrupoResponse")]
        void CrearNotaOpcionGrupo(KiiniNet.Entities.Operacion.NotaOpcionGrupo notaOpcionGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/ObtenerNotasUsuario", ReplyAction="http://tempuri.org/IServiceNota/ObtenerNotasUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasUsuario> ObtenerNotasUsuario(int idUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/ObtenerNotasOpcion", ReplyAction="http://tempuri.org/IServiceNota/ObtenerNotasOpcionResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasOpcion> ObtenerNotasOpcion(int idUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNota/ObtenerNotasGrupo", ReplyAction="http://tempuri.org/IServiceNota/ObtenerNotasGrupoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasUsuario> ObtenerNotasGrupo(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNotaChannel : KiiniHelp.ServiceNota.IServiceNota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNotaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceNota.IServiceNota>, KiiniHelp.ServiceNota.IServiceNota {
        
        public ServiceNotaClient() {
        }
        
        public ServiceNotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearNotaGeneralUsuario(KiiniNet.Entities.Operacion.NotaGeneral notaGeneral) {
            base.Channel.CrearNotaGeneralUsuario(notaGeneral);
        }
        
        public void CrearNotaOpcionUsuario(KiiniNet.Entities.Operacion.NotaOpcionUsuario notaOpcionUsuario) {
            base.Channel.CrearNotaOpcionUsuario(notaOpcionUsuario);
        }
        
        public void CrearNotaOpcionGrupo(KiiniNet.Entities.Operacion.NotaOpcionGrupo notaOpcionGrupo) {
            base.Channel.CrearNotaOpcionGrupo(notaOpcionGrupo);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasUsuario> ObtenerNotasUsuario(int idUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerNotasUsuario(idUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasOpcion> ObtenerNotasOpcion(int idUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerNotasOpcion(idUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperNotasUsuario> ObtenerNotasGrupo(int idUsuario) {
            return base.Channel.ObtenerNotasGrupo(idUsuario);
        }
    }
}
