//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaTipoCampoMascara {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaTipoCampoMascara.IServiceTipoCampoMascara")]
    public interface IServiceTipoCampoMascara {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCampoMascara/ObtenerTipoCampoMascara", ReplyAction="http://tempuri.org/IServiceTipoCampoMascara/ObtenerTipoCampoMascaraResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCampoMascara/TipoCampoMascaraId", ReplyAction="http://tempuri.org/IServiceTipoCampoMascara/TipoCampoMascaraIdResponse")]
        KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara TipoCampoMascaraId(int idTipoCampo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoCampoMascaraChannel : KiiniHelp.ServiceSistemaTipoCampoMascara.IServiceTipoCampoMascara, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoCampoMascaraClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaTipoCampoMascara.IServiceTipoCampoMascara>, KiiniHelp.ServiceSistemaTipoCampoMascara.IServiceTipoCampoMascara {
        
        public ServiceTipoCampoMascaraClient() {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoCampoMascaraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoCampoMascara(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara TipoCampoMascaraId(int idTipoCampo) {
            return base.Channel.TipoCampoMascaraId(idTipoCampo);
        }
    }
}
