//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceNotificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNotificacion.IServiceNotificacion")]
    public interface IServiceNotificacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNotificacion/ObtenerTipos", ReplyAction="http://tempuri.org/IServiceNotificacion/ObtenerTiposResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoNotificacion> ObtenerTipos(bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNotificacionChannel : KiiniHelp.ServiceNotificacion.IServiceNotificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNotificacionClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceNotificacion.IServiceNotificacion>, KiiniHelp.ServiceNotificacion.IServiceNotificacion {
        
        public ServiceNotificacionClient() {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoNotificacion> ObtenerTipos(bool insertarSeleccion) {
            return base.Channel.ObtenerTipos(insertarSeleccion);
        }
    }
}
