//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSubGrupoUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSubGrupoUsuario.IServiceSubGrupoUsuario")]
    public interface IServiceSubGrupoUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuario", ReplyAction="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuarioByIdGrupo", ReplyAction="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuarioByIdGrupoRespon" +
            "se")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario> ObtenerSubGruposUsuarioByIdGrupo(int idGrupoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGrupoUsuario", ReplyAction="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGrupoUsuarioResponse")]
        KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idSubGrupo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSubGrupoUsuarioChannel : KiiniHelp.ServiceSubGrupoUsuario.IServiceSubGrupoUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSubGrupoUsuarioClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSubGrupoUsuario.IServiceSubGrupoUsuario>, KiiniHelp.ServiceSubGrupoUsuario.IServiceSubGrupoUsuario {
        
        public ServiceSubGrupoUsuarioClient() {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubGrupoUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerSubGruposUsuario(idGrupoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario> ObtenerSubGruposUsuarioByIdGrupo(int idGrupoUsuario) {
            return base.Channel.ObtenerSubGruposUsuarioByIdGrupo(idGrupoUsuario);
        }
        
        public KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idSubGrupo) {
            return base.Channel.ObtenerSubGrupoUsuario(idGrupoUsuario, idSubGrupo);
        }
    }
}
