//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceTicket {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTicket.IServiceTicket")]
    public interface IServiceTicket {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/CrearTicketAndroid", ReplyAction="http://tempuri.org/IServiceTicket/CrearTicketAndroidResponse")]
        KiiniNet.Entities.Operacion.Tickets.Ticket CrearTicketAndroid(int idUsuario, int idUsuarioSolicito, int idArbol, string latitudinicio, string longitudinicio, string fechaalta, string latitudfin, string longitudfin, string costo, int idCanal, bool campoRandom, bool esTercero, bool esMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/CrearTicket", ReplyAction="http://tempuri.org/IServiceTicket/CrearTicketResponse")]
        KiiniNet.Entities.Operacion.Tickets.Ticket CrearTicket(int idUsuario, int idUsuarioSolicito, int idArbol, System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperCampoMascaraCaptura> lstCaptura, int idCanal, bool campoRandom, bool esTercero, bool esMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerTicketsUsuario", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerTicketsUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperTickets> ObtenerTicketsUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerTickets", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerTicketsResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperTickets> ObtenerTickets(int idUsuario, System.Collections.Generic.List<int> estatus, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerDetalleTicket", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerDetalleTicketResponse")]
        KiiniNet.Entities.Helper.HelperDetalleTicket ObtenerDetalleTicket(int idTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerTicket", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerTicketResponse")]
        KiiniNet.Entities.Helper.HelperTicketDetalle ObtenerTicket(int idTicket, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerDetalleTicketNoRegistrado", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerDetalleTicketNoRegistradoResponse")]
        KiiniNet.Entities.Helper.HelperDetalleTicket ObtenerDetalleTicketNoRegistrado(int idTicket, string cveRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/GeneraPreticket", ReplyAction="http://tempuri.org/IServiceTicket/GeneraPreticketResponse")]
        KiiniNet.Entities.Operacion.Tickets.PreTicket GeneraPreticket(int idArbol, int idUsuarioSolicita, int idUsuarioLevanto, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/CapturaCasillaTicket", ReplyAction="http://tempuri.org/IServiceTicket/CapturaCasillaTicketResponse")]
        System.Collections.Generic.List<int> CapturaCasillaTicket(int idTicket, string nombreCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ObtenerPreticketCorreo", ReplyAction="http://tempuri.org/IServiceTicket/ObtenerPreticketCorreoResponse")]
        KiiniNet.Entities.Operacion.Tickets.PreTicketCorreo ObtenerPreticketCorreo(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTicket/ConfirmaPreTicket", ReplyAction="http://tempuri.org/IServiceTicket/ConfirmaPreTicketResponse")]
        void ConfirmaPreTicket(string guid, int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTicketChannel : KiiniHelp.ServiceTicket.IServiceTicket, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTicketClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceTicket.IServiceTicket>, KiiniHelp.ServiceTicket.IServiceTicket {
        
        public ServiceTicketClient() {
        }
        
        public ServiceTicketClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTicketClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTicketClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTicketClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KiiniNet.Entities.Operacion.Tickets.Ticket CrearTicketAndroid(int idUsuario, int idUsuarioSolicito, int idArbol, string latitudinicio, string longitudinicio, string fechaalta, string latitudfin, string longitudfin, string costo, int idCanal, bool campoRandom, bool esTercero, bool esMail) {
            return base.Channel.CrearTicketAndroid(idUsuario, idUsuarioSolicito, idArbol, latitudinicio, longitudinicio, fechaalta, latitudfin, longitudfin, costo, idCanal, campoRandom, esTercero, esMail);
        }
        
        public KiiniNet.Entities.Operacion.Tickets.Ticket CrearTicket(int idUsuario, int idUsuarioSolicito, int idArbol, System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperCampoMascaraCaptura> lstCaptura, int idCanal, bool campoRandom, bool esTercero, bool esMail) {
            return base.Channel.CrearTicket(idUsuario, idUsuarioSolicito, idArbol, lstCaptura, idCanal, campoRandom, esTercero, esMail);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperTickets> ObtenerTicketsUsuario(int idUsuario) {
            return base.Channel.ObtenerTicketsUsuario(idUsuario);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperTickets> ObtenerTickets(int idUsuario, System.Collections.Generic.List<int> estatus, int pageIndex, int pageSize) {
            return base.Channel.ObtenerTickets(idUsuario, estatus, pageIndex, pageSize);
        }
        
        public KiiniNet.Entities.Helper.HelperDetalleTicket ObtenerDetalleTicket(int idTicket) {
            return base.Channel.ObtenerDetalleTicket(idTicket);
        }
        
        public KiiniNet.Entities.Helper.HelperTicketDetalle ObtenerTicket(int idTicket, int idUsuario) {
            return base.Channel.ObtenerTicket(idTicket, idUsuario);
        }
        
        public KiiniNet.Entities.Helper.HelperDetalleTicket ObtenerDetalleTicketNoRegistrado(int idTicket, string cveRegistro) {
            return base.Channel.ObtenerDetalleTicketNoRegistrado(idTicket, cveRegistro);
        }
        
        public KiiniNet.Entities.Operacion.Tickets.PreTicket GeneraPreticket(int idArbol, int idUsuarioSolicita, int idUsuarioLevanto, string observaciones) {
            return base.Channel.GeneraPreticket(idArbol, idUsuarioSolicita, idUsuarioLevanto, observaciones);
        }
        
        public System.Collections.Generic.List<int> CapturaCasillaTicket(int idTicket, string nombreCampo) {
            return base.Channel.CapturaCasillaTicket(idTicket, nombreCampo);
        }
        
        public KiiniNet.Entities.Operacion.Tickets.PreTicketCorreo ObtenerPreticketCorreo(string guid) {
            return base.Channel.ObtenerPreticketCorreo(guid);
        }
        
        public void ConfirmaPreTicket(string guid, int idUsuario) {
            base.Channel.ConfirmaPreTicket(guid, idUsuario);
        }
    }
}
