//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IServiceUsuarios")]
    public interface IServiceUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/GuardarUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/GuardarUsuarioResponse")]
        void GuardarUsuario(KiiniNet.Entities.Operacion.Usuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/RegistrarCliente", ReplyAction="http://tempuri.org/IServiceUsuarios/RegistrarClienteResponse")]
        int RegistrarCliente(KiiniNet.Entities.Operacion.Usuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/GuardarUsuarioAdicional", ReplyAction="http://tempuri.org/IServiceUsuarios/GuardarUsuarioAdicionalResponse")]
        void GuardarUsuarioAdicional(string nombre, string ap, string correo, string celular, string edad, string numeroTarjeta, string fechavto, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerUsuarios", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerUsuariosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuarios(System.Nullable<int> idTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerDetalleUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerDetalleUsuarioResponse")]
        KiiniNet.Entities.Operacion.Usuarios.Usuario ObtenerDetalleUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerUsuariosByGrupo", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerUsuariosByGrupoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuariosByGrupo(int idGrupo, int idNivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerUsuariosByGrupoAtencion", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerUsuariosByGrupoAtencionResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuariosByGrupoAtencion(int idGrupo, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ActualizarUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/ActualizarUsuarioResponse")]
        void ActualizarUsuario(int idUsuario, KiiniNet.Entities.Operacion.Usuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/GuardarFoto", ReplyAction="http://tempuri.org/IServiceUsuarios/GuardarFotoResponse")]
        void GuardarFoto(int idUsuario, byte[] imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerFoto", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerFotoResponse")]
        byte[] ObtenerFoto(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/HabilitarUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/HabilitarUsuarioResponse")]
        void HabilitarUsuario(int idUsuario, bool habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerAtendedoresEncuesta", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerAtendedoresEncuestaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerAtendedoresEncuesta(int idUsuario, System.Collections.Generic.List<System.Nullable<int>> encuestas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ValidaUserName", ReplyAction="http://tempuri.org/IServiceUsuarios/ValidaUserNameResponse")]
        bool ValidaUserName(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ValidaConfirmacion", ReplyAction="http://tempuri.org/IServiceUsuarios/ValidaConfirmacionResponse")]
        bool ValidaConfirmacion(int idUsuario, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ValidaCodigoVerificacionSms", ReplyAction="http://tempuri.org/IServiceUsuarios/ValidaCodigoVerificacionSmsResponse")]
        string ValidaCodigoVerificacionSms(int idUsuario, int idTipoNotificacion, int idTelefono, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/EnviaCodigoVerificacionSms", ReplyAction="http://tempuri.org/IServiceUsuarios/EnviaCodigoVerificacionSmsResponse")]
        void EnviaCodigoVerificacionSms(int idUsuario, int idTipoNotificacion, int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ActualizarTelefono", ReplyAction="http://tempuri.org/IServiceUsuarios/ActualizarTelefonoResponse")]
        void ActualizarTelefono(int idUsuario, int idTelefono, string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ConfirmaCuenta", ReplyAction="http://tempuri.org/IServiceUsuarios/ConfirmaCuentaResponse")]
        void ConfirmaCuenta(int idUsuario, string password, System.Collections.Generic.Dictionary<int, string> confirmaciones, System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.PreguntaReto> pregunta, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/BuscarUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/BuscarUsuarioResponse")]
        KiiniNet.Entities.Operacion.Usuarios.Usuario BuscarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/BuscarUsuarios", ReplyAction="http://tempuri.org/IServiceUsuarios/BuscarUsuariosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> BuscarUsuarios(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/EnviaCodigoVerificacionCorreo", ReplyAction="http://tempuri.org/IServiceUsuarios/EnviaCodigoVerificacionCorreoResponse")]
        string EnviaCodigoVerificacionCorreo(int idUsuario, int idTipoNotificacion, int idCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ValidaCodigoVerificacionCorreo", ReplyAction="http://tempuri.org/IServiceUsuarios/ValidaCodigoVerificacionCorreoResponse")]
        void ValidaCodigoVerificacionCorreo(int idUsuario, int idTipoNotificacion, string link, int idCorreo, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ValidaRespuestasReto", ReplyAction="http://tempuri.org/IServiceUsuarios/ValidaRespuestasRetoResponse")]
        void ValidaRespuestasReto(int idUsuario, System.Collections.Generic.Dictionary<int, string> preguntasReto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuarios/ObtenerDatosTicketUsuario", ReplyAction="http://tempuri.org/IServiceUsuarios/ObtenerDatosTicketUsuarioResponse")]
        KiiniNet.Entities.Helper.HelperUsuario ObtenerDatosTicketUsuario(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuariosChannel : KiiniHelp.ServiceUsuario.IServiceUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuariosClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceUsuario.IServiceUsuarios>, KiiniHelp.ServiceUsuario.IServiceUsuarios {
        
        public ServiceUsuariosClient() {
        }
        
        public ServiceUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GuardarUsuario(KiiniNet.Entities.Operacion.Usuarios.Usuario usuario) {
            base.Channel.GuardarUsuario(usuario);
        }
        
        public int RegistrarCliente(KiiniNet.Entities.Operacion.Usuarios.Usuario usuario) {
            return base.Channel.RegistrarCliente(usuario);
        }
        
        public void GuardarUsuarioAdicional(string nombre, string ap, string correo, string celular, string edad, string numeroTarjeta, string fechavto, string cvv) {
            base.Channel.GuardarUsuarioAdicional(nombre, ap, correo, celular, edad, numeroTarjeta, fechavto, cvv);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuarios(System.Nullable<int> idTipoUsuario) {
            return base.Channel.ObtenerUsuarios(idTipoUsuario);
        }
        
        public KiiniNet.Entities.Operacion.Usuarios.Usuario ObtenerDetalleUsuario(int idUsuario) {
            return base.Channel.ObtenerDetalleUsuario(idUsuario);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuariosByGrupo(int idGrupo, int idNivel) {
            return base.Channel.ObtenerUsuariosByGrupo(idGrupo, idNivel);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerUsuariosByGrupoAtencion(int idGrupo, bool insertarSeleccion) {
            return base.Channel.ObtenerUsuariosByGrupoAtencion(idGrupo, insertarSeleccion);
        }
        
        public void ActualizarUsuario(int idUsuario, KiiniNet.Entities.Operacion.Usuarios.Usuario usuario) {
            base.Channel.ActualizarUsuario(idUsuario, usuario);
        }
        
        public void GuardarFoto(int idUsuario, byte[] imagen) {
            base.Channel.GuardarFoto(idUsuario, imagen);
        }
        
        public byte[] ObtenerFoto(int idUsuario) {
            return base.Channel.ObtenerFoto(idUsuario);
        }
        
        public void HabilitarUsuario(int idUsuario, bool habilitado) {
            base.Channel.HabilitarUsuario(idUsuario, habilitado);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> ObtenerAtendedoresEncuesta(int idUsuario, System.Collections.Generic.List<System.Nullable<int>> encuestas) {
            return base.Channel.ObtenerAtendedoresEncuesta(idUsuario, encuestas);
        }
        
        public bool ValidaUserName(string nombreUsuario) {
            return base.Channel.ValidaUserName(nombreUsuario);
        }
        
        public bool ValidaConfirmacion(int idUsuario, string guid) {
            return base.Channel.ValidaConfirmacion(idUsuario, guid);
        }
        
        public string ValidaCodigoVerificacionSms(int idUsuario, int idTipoNotificacion, int idTelefono, string codigo) {
            return base.Channel.ValidaCodigoVerificacionSms(idUsuario, idTipoNotificacion, idTelefono, codigo);
        }
        
        public void EnviaCodigoVerificacionSms(int idUsuario, int idTipoNotificacion, int idTelefono) {
            base.Channel.EnviaCodigoVerificacionSms(idUsuario, idTipoNotificacion, idTelefono);
        }
        
        public void ActualizarTelefono(int idUsuario, int idTelefono, string numero) {
            base.Channel.ActualizarTelefono(idUsuario, idTelefono, numero);
        }
        
        public void ConfirmaCuenta(int idUsuario, string password, System.Collections.Generic.Dictionary<int, string> confirmaciones, System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.PreguntaReto> pregunta, string link) {
            base.Channel.ConfirmaCuenta(idUsuario, password, confirmaciones, pregunta, link);
        }
        
        public KiiniNet.Entities.Operacion.Usuarios.Usuario BuscarUsuario(string usuario) {
            return base.Channel.BuscarUsuario(usuario);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.Usuario> BuscarUsuarios(string usuario) {
            return base.Channel.BuscarUsuarios(usuario);
        }
        
        public string EnviaCodigoVerificacionCorreo(int idUsuario, int idTipoNotificacion, int idCorreo) {
            return base.Channel.EnviaCodigoVerificacionCorreo(idUsuario, idTipoNotificacion, idCorreo);
        }
        
        public void ValidaCodigoVerificacionCorreo(int idUsuario, int idTipoNotificacion, string link, int idCorreo, string codigo) {
            base.Channel.ValidaCodigoVerificacionCorreo(idUsuario, idTipoNotificacion, link, idCorreo, codigo);
        }
        
        public void ValidaRespuestasReto(int idUsuario, System.Collections.Generic.Dictionary<int, string> preguntasReto) {
            base.Channel.ValidaRespuestasReto(idUsuario, preguntasReto);
        }
        
        public KiiniNet.Entities.Helper.HelperUsuario ObtenerDatosTicketUsuario(int idUsuario) {
            return base.Channel.ObtenerDatosTicketUsuario(idUsuario);
        }
    }
}
